---

version: '2'
services:
  zookeeper:
    image: wurstmeister/zookeeper
    ports:
      - "2181:2181"
    networks: 
      - data-stack-net
  kafka:
    image: wurstmeister/kafka
    ports:
      - "9092"
    networks: 
      - data-stack-net
    environment:
      KAFKA_ADVERTISED_HOST_NAME: 172.20.0.1
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    
networks: 
    data-stack-net: