---

- name: Stop & Destroy Data Cluster
  hosts: localhost
  connection: local
  gather_facts: no
  tasks: 
    - include: roles/nifi/tasks/destroy.yml
    - include: roles/airflow/tasks/destroy.yml
    - include: roles/webapp/tasks/destroy.yml
    - include: roles/kafka/tasks/destroy.yml