---

-	name: Update yum cache
	yum: update_cache=yes
	when: ansible_os_family == "RedHat"

-	name: Upgrade all packages
	yum: name=* state=latest

-	name: Install python setup tools
	yum: name=python-setuptools
	tags: docker

-	name: Install Pypi
	easy_install: name=pip
	tags: docker

# Install docker

-	name: Install docker-py
	pip: name=docker-py
	tags: docker

-	name: Install Docker
	yum: name=docker state=latest
	tags: docker

-	name: Ensure docker is functional
	service: name=docker state=running
	tags: docker